# Generated by Django 4.2.7 on 2023-12-27 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_nickname'),
        ('app1', '0003_salesorder_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nick', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.nickname')),
            ],
        ),
    ]
